apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2048m
      memory: 1Gi
    requests:
      cpu: 2048m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: smregistrering
          namespace: teamsykmelding
          cluster: prod-fss
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvregpapirsm
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://smregistrering-backend.nais.adeo.no"
  kafka:
    pool: nav-prod
  env:
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password
    - name: SMREGISTERINGB_BACKEND_DB_URL
      value: jdbc:postgresql://A01DBVL009.adeo.no:5432/smregistrering-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: SMREGISTERING_URL
      value: smregistrering.nais.adeo.no
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.intern.nav.no/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: HENT_DOKUMENT_URL
      value: https://saf.intern.nav.no
    - name: SAFJOURNALPOST_GRAPHQL_PATH
      value: https://saf.intern.nav.no/graphql
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://prod-fss.teamsykefravr.syfo-tilgangskontroll/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no
    - name: SYFOSMPAPIR_REGLER_ENDPOINT_URL
      value: https://syfosmpapirregler.nais.adeo.no
    - name: SYFOSMPAPIRREGLER_SCOPE
      value: api://prod-fss.teamsykmelding.syfosmpapirregler/.default
    - name: KUHR_SAR_API_SCOPE
      value: api://prod-fss.teamkuhr.kuhr-sar-api/.default
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.nais.adeo.no
