apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering-backend
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvregpapirsm
        mountPath: /secrets/serviceuser
      - kvPath: /azuread/data/prod/creds/smregistrering-backend
        mountPath: /secrets/azuread/smregistrering-backend
      - kvPath: /kv/prod/fss/smregistrering-backend/default
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://smregistrering-backend.nais.adeo.no"
  env:
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: SMREGISTERINGB_BACKEND_DB_URL
      value: jdbc:postgresql://A01DBVL009.adeo.no:5432/smregistrering-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: OIDC_WELL_KNOWN_URI
      value: /secrets/default/oidcWellKnownUri
    - name: SMREGISTERING_BACKEND_CLIENT_ID_PATH
      value: /secrets/azuread/smregistrering-backend/client_id
    - name: SMREGISTERING_URL
      value: smregistrering.nais.adeo.no
    - name: HENT_DOKUMENT_URL
      value: https://saf.nais.adeo.no/
