apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering-backend
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvregpapirsm
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://smregistrering-backend.nais.adeo.no"
  env:
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password