apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering-backend
  namespace: default
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvregpapirsm
        mountPath: /secrets/serviceuser
      - kvPath: /azuread/data/dev/creds/smregistrering-backend
        mountPath: /secrets/azuread/smregistrering-backend
      - kvPath: /kv/preprod/fss/smregistrering-backend/default
        mountPath: /secrets/default
      - kvPath: /azuread/data/dev/creds/syfosmpapirregler
        mountPath: /secrets/azuread/syfosmpapirregler
  webproxy: true
  ingresses:
    - "https://smregistrering-backend.nais.preprod.local"
  env:
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SMREGISTERINGB_BACKEND_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/smregistrering-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: OIDC_WELL_KNOWN_URI
      value: /secrets/default/oidcWellKnownUri
    - name: SMREGISTERING_BACKEND_CLIENT_ID_PATH
      value: /secrets/azuread/smregistrering-backend/client_id
    - name: SMREGISTERING_URL
      value: smregistrering.nais.preprod.local
    - name: HENT_DOKUMENT_URL
      value: https://saf-q1.nais.preprod.local/
    - name: AKTOR_REGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.nais.preprod.local/rest/journalpostapi/v1/journalpost
    - name: MQ_SYFOSERVICE_QUEUE_NAME
      value: QA.Q1_EIA_SYFO_OUTBOUND
    - name: MQ_HOST_NAME
      value: b27apvl177.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC04
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMPAPIRMOTTAK
    - name: MQ_USERNAME
      value: /secrets/default/mqUsername
    - name: MQ_PASSWORD
      value: /secrets/default/mqPassword
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: SYFOSMPAIR_REGLER_CLIENT_ID_PATH
      value: /secrets/azuread/syfosmpapirregler/client_id
    - name: SMREGISTERING_BACKEND_CLIENT_SECRET_PATH
      value: /secrets/azuread/smregistrering-backend/client_secret
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: 32e36aa5-1d12-452a-9b1e-9f3f557cbb4d
