apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: smregistrering-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: smregistrering
            envVarPrefix: NAIS_DATABASE
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        tier: db-f1-micro
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 50m
      memory: 750Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syk-dig
          namespace: teamsykmelding
          cluster: dev-gcp
    outbound:
      rules:
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmpapirregler
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: smtss
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfohelsenettproxy
      external:
        - host: pdl-api.dev-fss-pub.nais.io
        - host: saf.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
        - host: graph.microsoft.com
        - host: dokarkiv.dev-fss-pub.nais.io
  vault:
    enabled: false
  secureLogs:
    enabled: true
  kafka:
    pool: nav-dev
  env:
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: HELSENETT_ENDPOINT_URL
      value: http://syfohelsenettproxy
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SAF_URL
      value: https://saf.dev-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf-q1/.default
    - name: OPPGAVE_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: ISTILGANGSKONTROLL_SCOPE
      value: api://dev-gcp.teamsykefravr.istilgangskontroll/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: SYFOSMPAPIRREGLER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmpapirregler/.default
    - name: SYFOSMREGISTER_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmregister/.default
    - name: SMTSS_API_SCOPE
      value: api://dev-gcp.teamsykmelding.smtss/.default
