apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smregistrering-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: smregistrering
          namespace: teamsykmelding
          cluster: dev-fss
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvregpapirsm
        mountPath: /secrets/serviceuser
      - kvPath: /azuread/data/dev/creds/smregistrering-backend
        mountPath: /secrets/azuread/smregistrering-backend
      - kvPath: /kv/preprod/fss/smregistrering-backend/teamsykmelding
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://smregistrering-backend.nais.preprod.local"
  env:
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SMREGISTERINGB_BACKEND_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/smregistrering-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: OIDC_WELL_KNOWN_URI
      value: /secrets/default/oidcWellKnownUri
    - name: SMREGISTERING_BACKEND_CLIENT_ID_PATH
      value: /secrets/azuread/smregistrering-backend/client_id
    - name: SMREGISTERING_URL
      value: smregistrering.dev.adeo.no
    - name: AKTOR_REGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: DOK_ARKIV_URL
      value: https://dokarkiv-q1.nais.preprod.local/rest/journalpostapi/v1/journalpost
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: SMREGISTERING_BACKEND_CLIENT_SECRET_PATH
      value: /secrets/azuread/smregistrering-backend/client_secret
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://dev-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: HENT_DOKUMENT_URL
      value: https://saf-q1.nais.preprod.local/
    - name: SAFJOURNALPOST_GRAPHQL_PATH
      value: https://saf-q1.nais.preprod.local/graphql
    - name: SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.nais.preprod.local/api/v1/oppgaver
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://dev-fss.teamsykefravr.syfo-tilgangskontroll/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: SYFOSMPAPIR_REGLER_ENDPOINT_URL
      value: https://syfosmpapirregler.nais.preprod.local
    - name: SYFOSMPAPIRREGLER_SCOPE
      value: api://dev-fss.teamsykmelding.syfosmpapirregler/.default